/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Akte005RouteImport } from './routes/akte-005'
import { Route as Akte004RouteImport } from './routes/akte-004'
import { Route as Akte003RouteImport } from './routes/akte-003'
import { Route as Akte002RouteImport } from './routes/akte-002'
import { Route as AkteRouteImport } from './routes/akte'
import { Route as IndexRouteImport } from './routes/index'

const Akte005Route = Akte005RouteImport.update({
  id: '/akte-005',
  path: '/akte-005',
  getParentRoute: () => rootRouteImport,
} as any)
const Akte004Route = Akte004RouteImport.update({
  id: '/akte-004',
  path: '/akte-004',
  getParentRoute: () => rootRouteImport,
} as any)
const Akte003Route = Akte003RouteImport.update({
  id: '/akte-003',
  path: '/akte-003',
  getParentRoute: () => rootRouteImport,
} as any)
const Akte002Route = Akte002RouteImport.update({
  id: '/akte-002',
  path: '/akte-002',
  getParentRoute: () => rootRouteImport,
} as any)
const AkteRoute = AkteRouteImport.update({
  id: '/akte',
  path: '/akte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akte': typeof AkteRoute
  '/akte-002': typeof Akte002Route
  '/akte-003': typeof Akte003Route
  '/akte-004': typeof Akte004Route
  '/akte-005': typeof Akte005Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akte': typeof AkteRoute
  '/akte-002': typeof Akte002Route
  '/akte-003': typeof Akte003Route
  '/akte-004': typeof Akte004Route
  '/akte-005': typeof Akte005Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akte': typeof AkteRoute
  '/akte-002': typeof Akte002Route
  '/akte-003': typeof Akte003Route
  '/akte-004': typeof Akte004Route
  '/akte-005': typeof Akte005Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akte'
    | '/akte-002'
    | '/akte-003'
    | '/akte-004'
    | '/akte-005'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/akte' | '/akte-002' | '/akte-003' | '/akte-004' | '/akte-005'
  id:
    | '__root__'
    | '/'
    | '/akte'
    | '/akte-002'
    | '/akte-003'
    | '/akte-004'
    | '/akte-005'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkteRoute: typeof AkteRoute
  Akte002Route: typeof Akte002Route
  Akte003Route: typeof Akte003Route
  Akte004Route: typeof Akte004Route
  Akte005Route: typeof Akte005Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/akte-005': {
      id: '/akte-005'
      path: '/akte-005'
      fullPath: '/akte-005'
      preLoaderRoute: typeof Akte005RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akte-004': {
      id: '/akte-004'
      path: '/akte-004'
      fullPath: '/akte-004'
      preLoaderRoute: typeof Akte004RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akte-003': {
      id: '/akte-003'
      path: '/akte-003'
      fullPath: '/akte-003'
      preLoaderRoute: typeof Akte003RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akte-002': {
      id: '/akte-002'
      path: '/akte-002'
      fullPath: '/akte-002'
      preLoaderRoute: typeof Akte002RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akte': {
      id: '/akte'
      path: '/akte'
      fullPath: '/akte'
      preLoaderRoute: typeof AkteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkteRoute: AkteRoute,
  Akte002Route: Akte002Route,
  Akte003Route: Akte003Route,
  Akte004Route: Akte004Route,
  Akte005Route: Akte005Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
