// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyqkiuezglfjpwuwswmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cWtpdWV6Z2xmanB3dXdzd21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzMzUwNDYsImV4cCI6MjEwMDkxMTA0Nn0._ziIC1ouHH1Aqwo-epOkFpDPJ2WVs-vq4anHlTZBwlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});